---
  - name: add repo for php packages
    apt_repository: repo='ppa:ondrej/php' state=present
    
  - name: updating system
    apt:
      upgrade: yes
      update_cache: yes
      
  - name: install packages
    package: name={{ item }} state=present
    with_items: "{{ packages_for_nginx }}"

  - name: restarting php7.2-fpm
    systemd: name=php7.2-fpm state=started enabled=yes
    
  - name: removing default
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
      
   - name: copy conf file
     copy:
      src: "{{ role_path }}/files/default.conf"
      dest: /etc/nginx/conf.d/default.conf
      
   - name: reloading nginx
    systemd: name=nginx state=reloaded enabled=yes
          
   - name: copy info file
     copy:
      src: "{{ role_path }}/files/info.php"
      dest: /usr/share/nginx/html/info.php
